### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by Shura1oplot**
Various bugfixes and improvements:
1) transliterate filename instead of stripping non-ascii characters
2) improve scanned pdf detection
3) add test for tika extractor with scanned pdf files
4) fix race condition bug caused by flask threaded=True option
5) make es mapping settings configurable
6) use `unzip` for ZIP archives as it can detect non-ascii filenames encoding
7) add dependency to extract RAR archives

### CODE REVIEW

**Comment by pcbje** [comment]
secure_filename is used for a reason. I suggest adding an 'original_filename' field instead.

**Comment by Shura1oplot** [comment]
`secure_filename` truncates filenames like `привет.docx` into `docx` thus breaks extension detection. Can you describe the reason? Possibly I'll find a compromise solution.

**Comment by pcbje** [comment]
The filename is provided by the client and is used when versions of the file are written to disk later. There is nothing stopping the client from sending a filename like "../hello.txt" and thus write the file to a different location. This can have some bad consequences. (See http://flask-russian-docs.readthedocs.io/ru/latest/patterns/fileuploads.html)

It does sound a bit weird if Flask doesn't support Cyrillic filenames. One option is to not use the filename as base for written files, but then they become harder to work with later. Another is to transliterate the filename before calling secure_filename:
```python
from transliterate import detect_language, translit

language = detect_language(file.name) 
transliterated = translit(file.name, language, reversed=True)
filename = secure_filename(transliterated)
```

**Comment by Shura1oplot** [comment]
What do you think about replacing '\0' and '/' on *nix systems and '\\' with other illegal characters on windows? And escaping special file names: '.'. '..', 'CON', ...

**Comment by pcbje** [comment]
I'm not if I understand you correctly, but I don't think doing the sanitisation ourselves is a good idea.

**Comment by Shura1oplot** [comment]
I have found a library that can sanitize filenames: https://github.com/thombashi/pathvalidate. It is more permissive than `werkzeug.secure_filename`. Still some additional check are required for special filenames (`.`, `..`, `CON`, ...).

**Comment by pcbje** [comment]
Is there anything wrong with using both a transliterated + secured filename, as well as adding a new field containing the original filename? The UI may display the original name. To me this seems a bit cleaner.

Something like this in ```document.py```?

```python
def get_document(path, parent=None):
  ...
  language = detect_language(path) 
  transliterated = translit(path, language, reversed=True)
  doc.path = secure_filename(transliterated)
  doc.original_path = path
  ...
```

Or let 'path' be the original and have a 'secure_path' property we use when writing files to disk.

**Comment by Shura1oplot** [comment]
Transliteration is not universal and depends on dictionaries for particular languages. Moreover, detecting the language using a file path could be not accurate in case of mixing latin chars with non-latin. I'll make `secure_path` attribute of Document as a combination of docid and `secure_filename(path)`.

**Comment by Shura1oplot** [comment]
After all, I have to admit that your variant securing filenames is better. Now I have an issue with travis as it uses old version of Ubuntu. I`ll add mock script for pdfimage executable, it should fix tests.

**Comment by pcbje** [comment]
Great stuff! Thanks!

**Pull request merged**
